apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Lielik/democrm-helm-charts.git
    targetRevision: main
    path: .                      
    helm:
      valueFiles:
        - values.yaml           

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-crm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    
