---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-uri-secret
  namespace: demo-crm
spec:
  encryptedData:
    MONGODB_URI: AgAiRw++bZkeujr75hNo0V60RMrqlaaRR31Xy6Y79DXZMhc+2X1XovBW1J/sdgAGNljDrSyCoWZnHrsF9LZZtKI2n2/iHlNas/VK336Ov+fsLrdsDV/Ax5whiRJ51BKe/9QqBVjhjFDC7CDNWh2u4sKQYZAwXm0HUU1OLqdriMslGTb8ithx2TIAUCxIbTt38+N7mN5kAOP4jgZKu87TxU5N1lil3bgWNwPtnzRORVUJvDSL1WfkS14cSPwaZpTbLnSPtugmGCz5oisDSn4V6m2tdU/u6Br95kmgR08dutVdtO9B4T16R4mBb/CeMA7Z+tadDLA8J39V3mLiVBDLmdqLKPwV7mRcytZ2Ip6WeZXciZgi2IWr5D6/s+3cmc892fWjtrGaG7ARkuo4bUMihdxSdCLhskLv9JGfKliyXH8ycIgJ+osW6Wlx28Kl1/o8bJQ1d8nPTARsj5BOoxh6YcCguriT0HRrWNF2Heeos+Ug86SH8FgbDRZGNKrccUryFIXSbM2Oji7acH/vdMsl1aISpcmBSHPIR2LqNFD2RObegFKpF0JmZtsaht+A9QKG0UkxMmQPh2qpRfjDRjwb+AcXcXfoa4Gj1aKL1wqtWHAtlL+VqgUC6vx7Zagw0cQnEvd+MwfPaF8ztKxUXeV5HBytpQmIlLmcuHJ51YebpIhn3p4lm76Biq4ocrMpleN1qZwG5komV2UYnzmrwfRWDVs6yodN9jnOA9oerLm7hTbtSd/GetJgD36its49UHWQ7tfXbvSutPucPdQ5dzsC/drdFzPZPk9inzjS55we/VmaT1ny1cjylJLgLobAH42qxUmQxLCiYBIlpJzqXlv2jDdj9tglINqmilQ=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-uri-secret
      namespace: demo-crm
